### ISSUE TITLE
tiny bug in NERDADataSetReader!

### ISSUE THREAD

**Issue by meti-94** [ebanalyse/NERDA#1]
Hi there!
In some cases, there is an error raised during iterating over DataLoder's batches and I believe, it is happened because of offset's list length! 
The error is like this:

`RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/collate.py", line 73, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/collate.py", line 73, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [150] at entry 0 and [151] at entry 1`

A quick and Unprincipled solution to fix it can be adding an extra line of code to truncate the list in `class NERDADataSetReader()`, this is worked for me! :)

`offsets = offsets[:self.max_len]`

**Comment by smaakage85** [comment]
Hi @meti-94 

Thank you so much for your feedback. I will look into it asap :)

/L

**Comment by smaakage85** [comment]
@meti-94 can you provide the sentence + tags, that triggered the error?

**Comment by smaakage85** [comment]
@meti-94 can you help with some code to reproduce this error? Please :S

**Comment by meti-94** [comment]
Hi, So sorry for the late answer, I am adding a text file that contains several records and link to my implementation, change the data source and see the error, please :)

`RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/collate.py", line 73, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/collate.py", line 73, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [150] at entry 0 and [151] at entry 6`

Implementation: https://github.com/meti-94/TextClassification/blob/main/BERT_NER.ipynb
Sample data: [sample.txt](https://github.com/ebanalyse/NERDA/files/6134364/sample.txt)

**Comment by liuhh02** [comment]
> Hi there!
> In some cases, there is an error raised during iterating over DataLoder's batches and I believe, it is happened because of offset's list length!
> The error is like this:
> 
> `RuntimeError: Caught RuntimeError in DataLoader worker process 0. Original Traceback (most recent call last): File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop data = fetcher.fetch(index) File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch return self.collate_fn(data) File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/collate.py", line 73, in default_collate return {key: default_collate([d[key] for d in batch]) for key in elem} File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/collate.py", line 73, in <dictcomp> return {key: default_collate([d[key] for d in batch]) for key in elem} File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate return torch.stack(batch, 0, out=out) RuntimeError: stack expects each tensor to be equal size, but got [150] at entry 0 and [151] at entry 1`
> 
> A quick and Unprincipled solution to fix it can be adding an extra line of code to truncate the list in `class NERDADataSetReader()`, this is worked for me! :)
> 
> `offsets = offsets[:self.max_len]`

Hello! I'm facing the same error as well. May I know where you are adding the line `offsets = offsets[:self.max_len]` to fix the error? Is it after line 96 https://github.com/ebanalyse/NERDA/blob/main/src/NERDA/preprocessing.py#L96?

**Comment by meti-94** [comment]
As I said before, that was not the best solution :)

**Comment by meti-94** [comment]
As a quick fix, I suggest adding a simple truncation statement after the 96th line! I would analyze the code to find a better solution as soon as possible! this repo could help me a lot! :)

**Comment by smaakage85** [comment]
Hi @meti-94 and @liuhh02 . Sorry to have kept you hanging for so long! Can you help with providing just an example of a  sentence, that causes this error?

**Comment by smaakage85** [comment]
... and if you have an idea for a solution, I would love, if you would make a Pull Request! :)

**Comment by NicholasJallan** [comment]
Hi there ! I have the very same issue with a custom training/validation set, even if it seems to have a proper size.
I would be very pleased if this problem could be fixed.

**Comment by meti-94** [comment]
Hi again :)
I came up with an explanation and a simple solution for the issue, you can check it out [here](https://github.com/ebanalyse/NERDA/pull/15)!

**Comment by smaakage85** [comment]
pull request merged! : )

**Comment by navychea** [comment]
In my case, it worked when I changed the value of num_workers to 0 in Dataloader :) However, I still cannot figure out what is the real problem of that error :(
