### ISSUE TITLE
how to get the acc , P and R by NERDA

### ISSUE THREAD

**Issue by Shengyu-Liu558** [ebanalyse/NERDA#10]
how to get the acc , P and R by NERDA?

**Comment by smaakage85** [comment]
I will look into this and get back to you ASAP : )

**Comment by Hansyvea** [comment]
you can use seqval package to evaluate, though it would be nicer for NERDA to evaluate performance after each epoch :)

**Comment by smaakage85** [comment]
Have not had the ressources for doing this, so sorry. If anyone dares, I would really love a Pull Request for this enhancement.

**Comment by smaakage85** [comment]
Hi again @Hansyvea and @Shengyu-Liu558 

With the latest release of NERDA (0.9.6), evaluate_performance() returns precision and recall for all tags.

Also, if you want to compute to compute accuracy, you can just run:

model.evaluate_performance(return_accuracy = True)

I close this issue.

Best,
Lars
