### ISSUE TITLE
Question about validation_set

### ISSUE THREAD

**Issue by Shengyu-Liu558** [ebanalyse/NERDA#11]
I want to ask a simple question. The parameters of the model have been set before model training. What is the purpose of the validation set in model training? Thank you！

**Comment by smaakage85** [comment]
The purpose of the validation set is to choose the best model/weights based on the validation performance i.e. performance on the validation data set, that has not been used for training as such. The model is evaluated at the end of each epoch.

Maybe take a look at: https://machinelearningmastery.com/difference-test-validation-datasets/

Did this clearify things?

Best, Lars

**Comment by Shengyu-Liu558** [comment]
Thank you，good answer！！
