### ISSUE TITLE
How to add a CRF layer?

### ISSUE THREAD

**Issue by Hansyvea** [ebanalyse/NERDA#12]
by observing the prediction output, i found many errors were made by wrong prefix. it is possible that a CRF layer as decoder could solve the problem

**Comment by smaakage85** [comment]
Hi again @Hansyvea . 

Thanks for input! that is also my experience.

I have not experience with adding CRF layers. Do you have a suggestion? With NERDA you can provide your own network, so I think, it could be implemented there?
