### ISSUE TITLE
not work with different pytorch/transformers version

### ISSUE THREAD

**Issue by Hansyvea** [ebanalyse/NERDA#13]
I tested the same dataset along with the same model and hyper parameters but in different versions of torch and transformers.
It raises error with torch 1.81 as the following:
TypeError: TextEncodeInput must be Union[TextInputSequence, Tuple[InputSequence, InputSequence]]

However, it works fine in the environment in which I just had NERDA pip installed...

**Comment by smaakage85** [comment]
@Hansyvea thanks for feedback! You are absolutely correct. With so much happening on both 'transformers' and 'torch' at the moment it takes some work to keep 'NERDA' up to date! If you are able to fix the issue, I would really appreciate a Pull Request!

**Comment by Dhruvit-Chaniyara** [comment]
tokenizer = AutoTokenizer.from_pretrained("bert-base-cased", use_fast=False)

add parameter, "use_fast=false" in tokenizer

https://huggingface.co/transformers/migration.html

**Comment by smaakage85** [comment]
thanks! I will fix this!

**Comment by smaakage85** [comment]
Thanks for your input @Dhruvit-Chaniyara  and @Hansyvea. I have fixed this in the new release.
