### ISSUE TITLE
How to save the model after training?

### ISSUE THREAD

**Issue by atoutou** [ebanalyse/NERDA#14]
I have trained a NERDA model and want to save the model but I can't find any function in the NERDA to do this.
How do I save the model?

<img width="648" alt="截圖 2021-04-19 下午5 12 29" src="https://user-images.githubusercontent.com/21039200/115211725-6df2d680-a132-11eb-9f67-10fcbfbc09f5.png">

**Comment by Hansyvea** [comment]
you could use the torch save and load method
```
import torch
torch.save(model, 'model.pt')
```
and load it back
model = torch.load('model.pt')

**Comment by atoutou** [comment]
Thanks for your quick reply. It works properly.
