### ISSUE TITLE
Save a trained model

### ISSUE THREAD

**Issue by alfredcs** [ebanalyse/NERDA#16]
Is there a way to save a trained model?

**Comment by yptheangel** [comment]
#14

**Comment by smaakage85** [comment]
Yes, you can use 'torch' built-in functions, like proposed in #14:

![image](https://user-images.githubusercontent.com/24368532/118937680-0fe22a80-b94e-11eb-9f7d-6ee44e80c3e8.png)

I will build a method NERDA, that does this! 

Best, Lars

**Comment by smaakage85** [comment]
hi again @alfredcs  

At long last I have implemented this (NERDA==1.0.0). See functions:

`python
model.save_network
`
`python
model.load_network_from_file
`

Thank you so much for you feedback.
