### ISSUE TITLE
Get confidence values for predicted tokens

### ISSUE THREAD

**Issue by Lolologist** [ebanalyse/NERDA#20]
It would be very useful if, for every prediction, we could see what the probability is of that prediction (and/or of all classes for that token).

**Comment by smaakage85** [comment]
Hi @Lolologist 

Thank you so much for your feedback.

I totally agree!

I have implemented an option for returning confidence scores in NERDA 0.9.7.

You can now compute confidence scores by:

``` python
model.predict(x, return_confidence=True)
model.predict_text(x, return_confidence=True)
```
