### ISSUE TITLE
Using .predict_text() method with an Iterable of text

### ISSUE THREAD

**Issue by hieuthehungry** [ebanalyse/NERDA#3]
Hello the awesome team behind this project!
I've been using this repo for some NER tasks recently, and it is fantastic and super easy to use! However, I would like to suggest that you should .predict_text() method able to run inference on multiple text instances rather than one instance at a time like now. It will be much more convenient and may allow for faster computation

**Comment by smaakage85** [comment]
HI @hieuthehungry 

Thank you so much! And thank you for your feedback.

Sounds like a good idea.... I encourage you to make a Pull Request, if you want to speed up the process. 

Best
Lars
