### ISSUE TITLE
Could you please explain how to load a local conll2003 formatted file?

### ISSUE THREAD

**Issue by Hansyvea** [ebanalyse/NERDA#4]
How could I save the trained model locally and load it next time?
didn't see this in the tutorial (Perhaps it is too easy... but I couldn't find a way)
Thanks in advance.

**Comment by furkan-celik** [comment]
You can read a file and convert to the same format. I have some txt files and I parsed them to a dictionary with sentences and labels keys which is the same structure you can see on ConLL dataset outputs. After creating that dictionary, both sentences and labels as lists, I have successfully trained model.

**Comment by smaakage85** [comment]
yes @furkan-celik .

Did this solve your issue, @Hansyvea ? 

I close this issue.

Best, Lars

**Comment by Hansyvea** [comment]
> 
> 
> yes @furkan-celik .
> 
> Did this solve your issue, @Hansyvea ?
> 
> I close this issue.
> 
> Best, Lars

yes, I do, thank you for your and furkan's reply!
