### ISSUE TITLE
'BertModel' object has no attribute 'name_or_path'

### ISSUE THREAD

**Issue by CyrusDobbs** [ebanalyse/NERDA#5]
Hi there - thanks for releasing your code and taking the time to read my issue!

I've just started to explore how NERDA works by trying to run the code from https://ebanalyse.github.io/NERDA/workflow/ but ran into the error of:

> KeyError: 'electra'

I then changed the transformer to 'bert-base-multilingual-uncased' but now I am getting the error of: 

> ModuleAttributeError: 'BertModel' object has no attribute 'name_or_path'

I can't see anyone else with the same issue online and my knowledge of transformers is poor. I'd really appreciate any help you could provide. 

Cheers

**Comment by CyrusDobbs** [comment]
Ah fixed it. My issue was some dependencies were outdated. I created a new virtualenv and started again.

**Comment by yazidhadni** [comment]
Hi, 
I have the same problem. 
Can you tell me how did you fix it please? Thanks in advance :)

**Comment by CyrusDobbs** [comment]
> Hi,
> I have the same problem.
> Can you tell me how did you fix it please? Thanks in advance :)

Hi,
It was an issue with the libraries dependencies that NERDA uses. I'd recommend using a fresh virtualenv for that particular project and reimporting NERDA and it's dependencies.

**Comment by yazidhadni** [comment]
I did, however the error is still here :( You installed NERDA version 0.8.8 ?
