### ISSUE TITLE
question about save model

### ISSUE THREAD

**Issue by Shengyu-Liu558** [ebanalyse/NERDA#6]
Hello, How to save the model that I have trained through code？

**Comment by yptheangel** [comment]
using pytorch syntax,

```
import torch
modelname = f'your_modelname_here.bin'
torch.save(model.network.state_dict(), modelname )
```

to load model,
`model.load_network_from_file(model_path=modelname)`

**Comment by Shengyu-Liu558** [comment]
When I load the trained model by "model.load_network_from_file(model_path=modelname)"，it is error, could I need to change the load code?

**Comment by Shengyu-Liu558** [comment]
next quesition

**Comment by smaakage85** [comment]
hi @Shengyu-Liu558 

With NERDA==1.0.0, see functions:

`python
model.save_network
`
`python
model.load_network_from_file
`

Thank you so much for you feedback.
