### ISSUE TITLE
troubles with 'device' parameter in models.py

### ISSUE THREAD

**Issue by Combo-Breaker** [ebanalyse/NERDA#8]
Hi there!

I have some troubles when I specify the device in NERDA model:

![image](https://user-images.githubusercontent.com/10671091/114407984-a5e99f00-9bb1-11eb-9dbe-4a26dc5d0e53.png)

At the same time, when I do not specify the device parameter, everything works just fine.
Looks like the trouble is in models.py [here](https://github.com/ebanalyse/NERDA/blob/main/src/NERDA/models.py#L153) : if `device != None`, `self.device` is not initialized.

**Comment by Combo-Breaker** [comment]
upd: I've created a [PR](https://github.com/ebanalyse/NERDA/pull/9), hope it is OK (: 

and thank you for your work, the model is very cool and easy to use

**Comment by smaakage85** [comment]
thank you so much, @Combo-Breaker . And thank you so much, for your pull request. I'll implement it asap.
